// AUTO-GENERATED by local-authority-silo-engine.
// DO NOT EDIT BY HAND. Regenerate via:
//   python3 generate.py --brand thornwell && python3 install_routes.py --brand thornwell

import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { ArrowUpRight, ChevronRight, ExternalLink } from "lucide-react";
import { BRAND, NAP, CTAS, SITE } from "@/lib/constants";
import CTASection from "@/components/CTASection";
import SchemaJsonLd from "@/components/SchemaJsonLd";
import Container from "@/components/ui/Container";
import SectionLabel from "@/components/ui/SectionLabel";
import Reveal from "@/components/ui/Reveal";
import { breadcrumbSchema } from "@/lib/schema";
import { IMG, unsplashUrl } from "@/lib/imagery";
import bundle from "@/lib/silo/content.json";

type Params = { params: { silo: string } };

type SiloPage = {
  type: "city_hub" | "service_in_city" | "blog";
  url: string;
  title: string;
  meta_description: string;
  city: string;
  city_key: string;
  state_abbr: string;
  state: string;
  country?: string;
  lat?: number;
  lng?: number;
  intro?: string;
  local_context?: string;
  service_details?: string;
  service_slug?: string;
  service_label?: string;
  service_blurb?: string;
  authority_citations?: Array<{ name: string; url: string; context?: string }>;
  authority_citation?: { name: string; url: string; context?: string };
  faq?: Array<{ q: string; a: string }>;
  image: string;
  image_alt: string;
  neighborhoods?: string[];
  jurisdiction?: { body: string; statute: string; url: string };
  city_hub_url?: string;
  national_service_url?: string;
};

const ALL_PAGES = bundle.pages as SiloPage[];
const FLAT_PAGES = ALL_PAGES.filter((p) => p.type !== "blog");

export const dynamic = "force-static";
export const dynamicParams = false;

export async function generateStaticParams() {
  return FLAT_PAGES.map((p) => ({ silo: p.url.replace(/^\//, "") }));
}

export function generateMetadata({ params }: Params): Metadata {
  const page = FLAT_PAGES.find((p) => p.url === `/${params.silo}`);
  if (!page) return {};
  return {
    title: `${page.title} | ${BRAND.name}`,
    description: page.meta_description,
    alternates: { canonical: `${SITE.url}${page.url}/` },
    openGraph: {
      title: page.title,
      description: page.meta_description,
      url: `${SITE.url}${page.url}/`,
      siteName: BRAND.name,
      type: "website",
    },
  };
}

function buildSchema(page: SiloPage) {
  const graph: any[] = [
    breadcrumbSchema([
      { name: "Home", url: "/" },
      { name: page.title, url: `${page.url}/` },
    ]),
  ];

  if (page.type === "city_hub") {
    graph.push({
      "@context": "https://schema.org",
      "@type": "ProfessionalService",
      "@id": `${SITE.url}${page.url}#localbusiness`,
      name: `${BRAND.name} - ${page.city}, ${page.state_abbr}`,
      url: `${SITE.url}${page.url}/`,
      telephone: NAP.phone.e164,
      areaServed: {
        "@type": "City",
        name: page.city,
        containedInPlace: { "@type": "State", name: page.state },
      },
      geo:
        page.lat && page.lng
          ? {
              "@type": "GeoCoordinates",
              latitude: page.lat,
              longitude: page.lng,
            }
          : undefined,
    });
  } else if (page.type === "service_in_city") {
    graph.push({
      "@context": "https://schema.org",
      "@type": "Service",
      "@id": `${SITE.url}${page.url}#service`,
      name: `${page.service_label} in ${page.city}, ${page.state_abbr}`,
      provider: { "@type": "Organization", name: BRAND.name, url: SITE.url },
      areaServed: { "@type": "City", name: page.city },
      description: page.service_blurb,
    });
  }

  if (page.faq && page.faq.length > 0) {
    graph.push({
      "@context": "https://schema.org",
      "@type": "FAQPage",
      speakable: {
        "@type": "SpeakableSpecification",
        cssSelector: ["summary", "details > p"],
      },
      mainEntity: page.faq.map((f) => ({
        "@type": "Question",
        name: f.q,
        acceptedAnswer: { "@type": "Answer", text: f.a },
      })),
    });
  }

  graph.push({
    "@context": "https://schema.org",
    "@type": "Person",
    "@id": `${SITE.url}#thornwell-lead`,
    name: "Pending real name from Thornwell team while the Team CMS is built",
    jobTitle: "Engagement Lead",
    worksFor: { "@type": "Organization", name: BRAND.name, url: SITE.url },
    url: SITE.url,
  });

  return graph;
}

export default function SiloFlatPage({ params }: Params) {
  const page = FLAT_PAGES.find((p) => p.url === `/${params.silo}`);
  if (!page) notFound();

  const cityPages = ALL_PAGES.filter((p) => p.city_key === page.city_key);
  const siblingServices = cityPages.filter(
    (p) => p.type === "service_in_city" && p.url !== page.url
  );
  const cityHub = cityPages.find((p) => p.type === "city_hub");
  const cityBlogs = cityPages.filter((p) => p.type === "blog");

  const heroImgId =
    page.type === "city_hub" ? IMG.heroBoardroom.id : IMG.strategySession.id;

  return (
    <>
      <SchemaJsonLd data={buildSchema(page)} />

      {/* HERO */}
      <section className="on-dark relative overflow-hidden bg-ink text-paper">
        <Image
          src={unsplashUrl(heroImgId, 2400, 78)}
          alt={page.image_alt}
          fill
          priority
          sizes="100vw"
          className="img-treat object-cover opacity-25"
        />
        <div aria-hidden className="absolute inset-0 hero-vignette" />

        <Container>
          <div className="relative pb-20 pt-32 md:pb-28 md:pt-40">
            <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-xs text-paper/60">
              <Link href="/" className="hover:text-paper">Home</Link>
              <ChevronRight className="h-3 w-3" />
              {cityHub && cityHub.url !== page.url ? (
                <>
                  <Link href={`${cityHub.url}/`} className="hover:text-paper">{page.city}</Link>
                  <ChevronRight className="h-3 w-3" />
                  <span className="text-paper/95">{page.service_label}</span>
                </>
              ) : (
                <span className="text-paper/95">{page.city}, {page.state_abbr}</span>
              )}
            </nav>

            <div className="mt-10 grid items-end gap-12 md:grid-cols-12">
              <div className="md:col-span-9">
                <SectionLabel
                  number="01"
                  label={page.type === "city_hub" ? `${page.state} coverage` : `${page.city} ${page.state_abbr}`}
                  variant="dark"
                />
                <h1 className="mt-8 font-serif text-display-xl font-semibold text-paper balance">
                  {page.title}.
                </h1>
                <p className="mt-8 max-w-2xl text-lg leading-relaxed text-paper/90">
                  {page.meta_description}
                </p>
                <div className="mt-10 flex flex-wrap gap-3">
                  <Link href={CTAS.primary.href} className="btn-primary-on-dark group">
                    <span>{CTAS.primary.label}</span>
                    <ArrowUpRight className="h-4 w-4 transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5" />
                  </Link>
                  <a href={NAP.phone.href} className="btn-ghost-on-dark">
                    {NAP.phone.display}
                  </a>
                </div>
              </div>
            </div>
          </div>
        </Container>
      </section>

      {/* BODY */}
      <section className="bg-paper">
        <Container>
          <div className="grid gap-16 py-20 md:grid-cols-12 md:py-28">
            <div className="md:col-span-7">
              <Reveal>
                <SectionLabel number="01" label="The work" />
                <h2 className="mt-6 font-serif text-display-md font-semibold text-navy-900 balance">
                  {page.type === "city_hub"
                    ? `${BRAND.name} in ${page.city}.`
                    : `${page.service_label} in ${page.city}.`}
                </h2>
                <div className="prose prose-slate mt-8 max-w-none text-[17px] leading-[1.85] text-navy-800">
                  {page.intro && <p>{page.intro}</p>}
                  {page.local_context && <p>{page.local_context}</p>}
                  {page.service_details && <p>{page.service_details}</p>}
                </div>
              </Reveal>

              {(page.authority_citations?.length || page.authority_citation) && (
                <Reveal className="mt-16" delay={0.05}>
                  <SectionLabel number="02" label="Local references" />
                  <ul className="mt-8 space-y-4">
                    {((page.authority_citations || []).concat(
                      page.authority_citation ? [page.authority_citation] : []
                    ) as Array<{ name: string; url: string; context?: string }>).map(
                      (a, i) =>
                        a && a.name ? (
                          <li key={i} className="flex gap-3 items-start">
                            <ExternalLink className="mt-1.5 h-4 w-4 flex-none text-gold-600" />
                            <div>
                              {a.url ? (
                                <a
                                  href={a.url}
                                  target="_blank"
                                  rel="noopener noreferrer"
                                  className="font-semibold text-navy-900 underline underline-offset-2"
                                >
                                  {a.name}
                                </a>
                              ) : (
                                <span className="font-semibold text-navy-900">{a.name}</span>
                              )}
                              {a.context && (
                                <p className="mt-1 text-sm text-navy-700">{a.context}</p>
                              )}
                            </div>
                          </li>
                        ) : null
                    )}
                  </ul>
                </Reveal>
              )}

              {page.faq && page.faq.length > 0 && (
                <Reveal className="mt-16" delay={0.05}>
                  <SectionLabel number="03" label="Frequently asked" />
                  <div className="mt-8 space-y-4">
                    {page.faq.map((f, i) => (
                      <details
                        key={i}
                        className="card p-6"
                      >
                        <summary className="cursor-pointer font-semibold text-navy-900">
                          {f.q}
                        </summary>
                        <p className="mt-3 text-[16px] leading-7 text-navy-800">{f.a}</p>
                      </details>
                    ))}
                  </div>
                </Reveal>
              )}
            </div>

            <aside className="md:col-span-5">
              <div className="sticky top-28 space-y-6">
                {page.type === "city_hub" && siblingServices.length > 0 && (
                  <div className="rounded-2xl border border-paper-edge bg-white p-7">
                    <div className="font-mono text-[11px] uppercase tracking-[0.18em] text-navy-700">
                      Service lines in {page.city}
                    </div>
                    <ul className="mt-5 space-y-2">
                      {siblingServices.slice(0, 8).map((s) => (
                        <li key={s.url}>
                          <Link
                            href={`${s.url}/`}
                            className="group flex items-center gap-3 rounded-xl border border-transparent p-3 no-underline transition hover:border-paper-edge hover:bg-paper-deep/40"
                          >
                            <span className="flex-1">
                              <span className="block font-semibold text-navy-900">
                                {s.service_label}
                              </span>
                            </span>
                            <ChevronRight className="h-4 w-4 text-navy-700 transition group-hover:translate-x-0.5" />
                          </Link>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {page.type === "service_in_city" && cityHub && (
                  <div className="rounded-2xl border border-paper-edge bg-navy-900 p-7 text-paper">
                    <div className="font-mono text-[11px] uppercase tracking-[0.18em] text-gold-400">
                      {page.city} city hub
                    </div>
                    <div className="mt-5 text-paper">
                      <p className="font-semibold">{cityHub.title}</p>
                      <p className="mt-2 text-sm text-paper/85">{cityHub.meta_description}</p>
                    </div>
                    <Link
                      href={`${cityHub.url}/`}
                      className="btn-primary-on-dark mt-7 w-full justify-between group"
                    >
                      <span>See full {page.city} coverage</span>
                      <ArrowUpRight className="h-4 w-4 transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5" />
                    </Link>
                  </div>
                )}

                {page.type === "service_in_city" && siblingServices.length > 0 && (
                  <div className="rounded-2xl border border-paper-edge bg-white p-7">
                    <div className="font-mono text-[11px] uppercase tracking-[0.18em] text-navy-700">
                      Related service lines
                    </div>
                    <ul className="mt-5 space-y-2">
                      {siblingServices.slice(0, 6).map((s) => (
                        <li key={s.url}>
                          <Link
                            href={`${s.url}/`}
                            className="group flex items-center gap-3 rounded-xl border border-transparent p-3 no-underline transition hover:border-paper-edge hover:bg-paper-deep/40"
                          >
                            <span className="flex-1">
                              <span className="block font-semibold text-navy-900">
                                {s.service_label}
                              </span>
                            </span>
                            <ChevronRight className="h-4 w-4 text-navy-700 transition group-hover:translate-x-0.5" />
                          </Link>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {page.neighborhoods && page.neighborhoods.length > 0 && (
                  <div className="rounded-2xl border border-paper-edge bg-paper-deep/30 p-7">
                    <div className="font-mono text-[11px] uppercase tracking-[0.18em] text-navy-700">
                      Service areas
                    </div>
                    <p className="mt-4 text-[15px] leading-7 text-navy-800">
                      {page.neighborhoods.join(", ")}
                    </p>
                  </div>
                )}
              </div>
            </aside>
          </div>
        </Container>
      </section>

      {cityBlogs.length > 0 && (
        <section className="bg-paper-deep/30">
          <Container>
            <div className="py-20 md:py-24">
              <SectionLabel number="04" label={`More from ${page.city}`} />
              <h2 className="mt-6 font-serif text-display-md font-semibold text-navy-900 balance">
                Field notes.
              </h2>
              <ul className="mt-10 grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
                {cityBlogs.map((b) => (
                  <li key={b.url}>
                    <Link
                      href={`${b.url}/`}
                      className="card flex h-full flex-col gap-3 p-6 transition hover:border-gold-500/50"
                    >
                      <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-navy-700">
                        {b.service_label}
                      </span>
                      <span className="font-serif text-[20px] leading-snug text-navy-900">
                        {b.title}
                      </span>
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          </Container>
        </section>
      )}

      <CTASection
        eyebrow="Engagement"
        number="05"
        title={`Run ${page.type === "service_in_city" ? page.service_label : "the operator stack"} in ${page.city}.`}
        description={`Foundation Sprint in week one. Operating cadence from week two. Weekly executive reports. Quarterly review. We respond inside one business day.`}
      />
    </>
  );
}
